#!/bin/bash

#FORMAT: python vis.py <topology file> <log file> <node color refresh True/False> <cycle interval>
#python vis.py topo.txt log.txt True 0.1
#python3 vis.py topo.txt log.txt True 0.2
python3 vis.py topo.txt ./../logger.txt True 0.2

#scenario 1
python3 vis.py ./../scenario_1/Topology.txt ./../scenario_1/logger.txt True 0.2


